<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="LAPTOP-LE02I758" name="com.testNGLearning.test.ValidateRetryLogicAtRun" tests="5" failures="0" timestamp="13 Sep 2019 14:44:29 GMT" time="77.097" errors="1">
  <testcase name="validatePageTitle" time="18.073" classname="com.testNGLearning.test.ValidateRetryLogicAtRun">
    <skipped/>
  </testcase> <!-- validatePageTitle -->
  <testcase name="validatePageTitle" time="12.421" classname="com.testNGLearning.test.ValidateRetryLogicAtRun">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;...123&gt; but was:&lt;...&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...123> but was:<...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at com.testNGLearning.test.ValidateRetryLogicAtRun.validatePageTitle(ValidateRetryLogicAtRun.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validatePageTitle -->
  <testcase name="validatePageTitle" time="13.040" classname="com.testNGLearning.test.ValidateRetryLogicAtRun">
    <skipped/>
  </testcase> <!-- validatePageTitle -->
  <testcase name="validatePageTitle" time="17.963" classname="com.testNGLearning.test.ValidateRetryLogicAtRun">
    <skipped/>
  </testcase> <!-- validatePageTitle -->
  <testcase name="validatePageTitle" time="15.600" classname="com.testNGLearning.test.ValidateRetryLogicAtRun">
    <skipped/>
  </testcase> <!-- validatePageTitle -->
</testsuite> <!-- com.testNGLearning.test.ValidateRetryLogicAtRun -->
